### PR TITLE
simplify fin

### PR DESCRIPTION
**Pull request by lol-fi**

### CODE REVIEW

**Review by fath0218 — APPROVED** [review]

**Comment by sethnielson** [comment]
There are a few problems with this. Sequence number should be the regular sequence number. It should not be 0. Also, I think you may have gotten rid of the wrong state. I said the only state that needed to go was the Close Wait.

Also, there's more to the last ack than just waiting for the last fin ack. You're supposed to wait for the last fin-ack in order. That is, if there is data that you sent followed by a fin, you are supposed to wait for an ack to all of that data and the fin ack'd last.

**Review by fath0218 — COMMENTED** [review]
It's better to keep the seq/ack numbers during the FIN handshake.

**Review by emengbenben — APPROVED** [review]

**Comment by lol-fi** [comment]
> There are a few problems with this. Sequence number should be the regular sequence number. It should not be 0. Also, I think you may have gotten rid of the wrong state. I said the only state that needed to go was the Close Wait.
> 
> Also, there's more to the last ack than just waiting for the last fin ack. You're supposed to wait for the last fin-ack in order. That is, if there is data that you sent followed by a fin, you are supposed to wait for an ack to all of that data and the fin ack'd last.
...
> It's better to keep the seq/ack numbers during the FIN handshake.

Updated, please check for correctness.

**Comment by lol-fi** [comment]
> It's better to keep the seq/ack numbers during the FIN handshake.

**Comment by sethnielson** [comment]
Still looks incorrect to me. Let's discuss in class

**Pull request merged**
