### PR TITLE
More detail of error handling and error fixing

### PR DESCRIPTION
**Pull request by jingpingjiao**
- Added detail for error handling
- Fixed format issue by commit/f784624023c83d3c5273622b430d1a7a442dd3d0

### CODE REVIEW

**Comment by fath0218** [comment]
Btw, we are going to use _b''_ to set the checkSum field before doing the checksum right?

**Review by emengbenben — APPROVED** [review]

**Review by heaventourist — APPROVED** [review]

**Review by HarleyCody — APPROVED** [review]

**Review by fath0218 — APPROVED** [review]

**Review by emengbenben — APPROVED** [review]

**Comment by sethnielson** [comment]
@jingpingjiao This pull has been approved, but there are conflicts with other recent changes. Please update one more time and I'll merge

**Review by vaikunthsd — APPROVED** [review]
Approved, but please resolve the conflicts before merging it to the main.

**Review by lol-fi — APPROVED** [review]

**Comment by jingpingjiao** [comment]
@sethnielson  Merged, please approve and merge. thx

**Pull request merged**
